name: Read package.json version

on:
  push:
    branches:
      - master

jobs:
  detect-src-change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Filter
        uses: dorny/paths-filter@v2
        id: filters
        with:
          filters: |
            src:
              - "src/include-github-actions/**"
              - "!src/include-github-actions/no-action-trigger-dir/**"
              - "!src/include-github-actions/no-action-trigger-file.txt"
    outputs:
      has-src-changed: ${{ steps.filters.outputs.src }}
  test-build-and-push-web-app:
    needs:
      - detect-src-change
    runs-on: ubuntu-latest
    steps:
      if: needs.detect-src-change.outputs.has-src-changed == 'true'
      - name: Checkout to master branch
        uses: actions/checkout@v3
      - name: Export VERSION
        shell: bash
        run: echo "test" > VERSION
      - name: Run test
        shell: bash
        run: make -C src/include-github-actions test
      - name: Read package.json
        run: |
          echo 'PACKAGE_JSON<<EOF' >> $GITHUB_ENV
          cat src/include-github-actions/package.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Echo version
        shell: bash
        env:
          VERSION: ${{fromJson(env.PACKAGE_JSON).version}}
        run: |
          make -C src/include-github-actions echo-version
