name: Read package.json version

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed
    paths:
      - "src/include-github-actions/**"

jobs:
  test-build-and-push-web-app:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to master branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
      - name: Export VERSION
        shell: bash
        run: echo "test" > VERSION
      - name: Run test
        shell: bash
        run: make -C src/include-github-actions test
      - name: Read package.json
        run: |
          echo 'PACKAGE_JSON<<EOF' >> $GITHUB_ENV
          cat src/include-github-actions/package.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Echo version
        shell: bash
        env:
          VERSION: ${{fromJson(env.PACKAGE_JSON).version}}
        run: |
          make -C src/include-github-actions echo-version
